#!/usr/bin/env python
# -*- coding: utf-8 -*-


###Adaptado de text2digits_es
units = {
    'cero': 0,
    'uno': 1,
    'un': 1,
    'una': 1,
    'dos': 2,
    'tres': 3,
    'cuatro': 4,
    'cinco': 5,
    'seis': 6,
    'siete': 7,
    'ocho': 8,
    'nueve': 9,
    'diez': 10,
    'once': 11,
    'doce': 12,
    'trece': 13,
    'catorce': 14,
    'quince': 15,
    'dieciséis': 16,
    'diecisiete': 17,
    'dieciocho': 18,
    'diecinueve': 19
}

tens = {
    'veinti': 20,
    'veinte': 20,
    'veintiuno': 21,
    'veintiuna': 21,
    'veintiun': 21,
    'veintiún': 21,
    'veintidos': 22,
    'veintidós': 22,
    'veintitrés': 23,
    'veintitres': 23,
    'veinticuatro': 24,
    'veinticinco': 25,
    'veintiséis': 26,
    'veintiseis': 26,
    'veintisiete': 27,
    'veintiocho': 28,
    'veintinueve': 29,
    'ventinueve': 29,
    'treinta': 30,
    'cuarenta': 40,
    'cincuenta': 50,
    'sesenta': 60,
    'setenta': 70,
    'ochenta': 80,
    'noventa': 90
}

hundreds = {
    'cien': 100,
    'ciento': 100,
    'doscientos': 200,
    'doscientas': 200,
    'trescientos': 300,
    'trescientas': 300,
    'cuatrocientos': 400,
    'cuatrocientas': 400,
    'quinientos': 500,
    'quinientas': 500,
    'seiscientos': 600,
    'seiscientas': 600,
    'setecientos': 700,
    'setecientas': 700,
    'ochocientos': 800,
    'ochocientas': 800,
    'novecientos': 900,
    'novecientas': 900
}

ordinals = {
    'primero': 1,
    'primera': 1,
    'segundo': 2,
    'segunda': 2,
    'tercero': 3,
    'tercera': 3,
    'cuarto': 4,
    'cuarta': 4,
    'quinto': 5,
    'quinta': 5,
    'sexto': 6,
    'sexta': 6,
    'séptimo': 7,
    'séptima': 7,
    'octavo': 8,
    'octava': 8,
    'novena': 9,
    'noveno': 9,
    'décimo': 10,
    'décima': 10,
    'undécimo': 11,
    'undécima': 11,
    'duodécimo': 12,
    'duodécima': 12,
    'vigésimo': 20,
    'vigésima': 20,
    'trigésimo': 30,
    'trigésima': 30,
    'cuadragésimo': 40,
    'cuadragésima': 40,
    'quincuagésimo': 50,
    'quincuagésima': 50,
    'sexagésimo': 60,
    'sexagésima': 60,
    'septuagésimo': 70,
    'septuagésima': 70,
    'octogésimo': 80,
    'octogésima': 80,
    'nonagésimo': 90,
    'nonagésima': 90,
    'centésimo': 100,
    'centésima': 100,
    'ducentésimo': 200,
    'ducentésima': 200,
    'tricentésimo': 300,
    'tricentésima': 300,
    'cuadrigentésimo': 400,
    'cuadrigentésima': 400,
    'quingentésimo': 500,
    'quingentésima': 500,
    'sexcentésimo': 600,
    'sexcentésima': 600,
    'septingentésimo': 700,
    'septingentésima': 700,
    'octingentésimo': 800,
    'octingentésima': 800,
    'noningentésimo': 900,
    'noningentésima': 900,
    'milésimo': 1000,
    'milésima': 1000
}

scales = {
    'centimetros': .01,
    'centímetros': .01,
    'centimos': .01,
    'centimo': .01,
    'céntimos': .01,
    'decimetros': .01,
    'decímetros': .01,
    'mil': 1000,
    'centiárea': 1,
    'centiarea': 1,
    'centiáreas': 1,
    'centiareas': 1,
    'hectáreas': 10 ** 4,
    'hectareas': 10 ** 4,
    'hectárea': 10 ** 4,
    'hectarea': 10 ** 4,
    'millones': 10 ** 6,
    'millón': 10 ** 6,
    'billones': 10 ** 12,
    'billón': 10 ** 12,
    'trillones': 10 ** 18,
    'trillón': 10 ** 18
}

numwords = {
    **units,
    **tens,
    **hundreds,
    **ordinals,
    **scales
}

commons = {"vale", "usted", "nombre", "buenos", "buenas", "hola", "dias","dia", 
                 "claro", "si", "asi", "ahora", "bien", "gracias", "gracia", "momento",
                 "favor", "por", "dice", "tan",  "manana", "hoy", "señor", "dni",
                 "bueno", "pues", "entonces", "solo", "ver", "aqui", "correcto", "vamos", 
                 "perdón", "decir", "verdad", "puedo", "ayudar", "hora", "mismo", "mira",
                  "cosa", "llamo", "mire", "quiero", "meno", "solamente", "luego", "va",
                  "voy", "hacer", "hace", "pone", "toda", "ahí", "creo", "sabe", "digo",
                   "dicho", "ejemplo", "quiere", "perfecto", "hecho", "entiendo", "ustedes",
                    "vez", "sale", "dijeron", "digame", "puede", "ano", "queda", 
                    "igual", "dijo", "se", "tal", "despues", "podría", "mejor", "tener", "ser",
                    "exactamente", "companera", "companero", "algun", "exacto", "dirigirme",
                    "cual", "indico", "pueda", "primero", "queria", "mes", "mese", "actualmente",
                    "venga", "estupendo", "agente", "llamaba", "llamas"
}
names= { 'arce', 'jenny', 'celia',  'eduardo',  'elden', 'roni',  'maika', 'paloma', 'katia', 'austin', 'idem',  'ariel', 'lando',  'eliana', 'chiles', 'wila', 'carolina', 'solis', 'nial', 'emerson',  'ignacio',  'renal',  'emma', 'senia',  'soraya',  'melina',  'isas',  'rendon', 'abonar', 'marios',  'arroa', 'kira', 'simon', 'amador', 'jennifer', 'rives', 'thalia',  'isaac', 'fray', 'nagra', 'elizabeth', 'store', 'sorra', 'susy', 'elsa', 'guido',  'yadira', 'quinga', 'afiles', 'suly', 'emir', 'aranza', 'mariano', 'reli', 'fax', 'nina', 'santos', 'angeles', 'mariluz', 'vernet', 'loli', 'agustin',  'galvan', 'lusa',  'acosta', 'raquel',  'lenin', 'faustino', 'ducato', 'lized', 'habit', 'jeremy', 'lana', 'atena', 'reina',  'sumana',  'gaby',  'pamela', 'ferrer', 'helena', 'paola', 'olvera', 'cathia',  'jani', 'ruben', 'share', 'ronde', 'senor', 'rana', 'flores', 'nuria', 'susana', 'andrea',    'yelisa', 'nicol', 'aaron',  'cosi', 'sexta', 'andres', 'elisa', 'adela', 'christopher', 'lorena', 'gladys', 'rebeca', 'ogen', 'silva', 'alexandra',  'ford', 'ledie',  'pablo',  'marzon', 'montse', 'urosa', 'gilma',  'lilla',  'katherine', 'gisela',  'ramos', 'tomas',  'kevin', 'fael', 'miguel',   'tony', 'lafal', 'mariela', 'bras', 'saul', 'lan', 'chile',  'yacom', 'yolisa',  'mino', 'paz', 'asus',  'astris', 'martha',  'vargas', 'maite', 'berger', 'sob',  'maraca', 'josefina', 'nip', 'hmm', 'sandra', 'mismo', 'chen', 'cibar',  'galvis', 'jana', 'frey', 'lisenda', 'camilar',  'ramon',  'pepe',  'marina', 'ruby', 'isela',   'cona', 'rangel',   'cristian', 'veronica', 'mirena',  'lady', 'brayan', 'ina', 'vicio',  'landa',  'sima','carola', 'ines', 'cintia', 'ibarra', 'fijare', 'rambla',  'marcela',  'senta', 'ismael',  'nuris', 'ivette', 'marcos', 'marta', 'trini', 'gustavo', 'roma',  'freddy',  'diego', 'violeta', 'carlos', 'lexas', 'paqui', 'yerem', 'pobla', 'mabel', 'rut',  'red', 'edith', 'nieves', 'amaya', 'alan', 'ospina', 'franklin', 'luz', 'graciel',  'noemi',  'arlem', 'esther', 'gisell',  'salina', 'bryan', 'semanica', 'alico',   'maribel', 'varas', 'norma', 'irina','anina', 'jerson', 'semar', 'lona', 'gustan', 'fatima',  'mandarian', 'angie', 'trac', 'quiles', 'racia', 'rice', 'ocana',   'diaz', 'ayala', 'eligio',  'isaias',  'liban', 'parra', 'maicu', 'selen', 'caray', 'marcia', 'abinal', 'como', 'johan', 'jonny',  'jocelyn', 'yerman',  'vahe', 'kte',  'carmen', 'moreno', 'maricarmen', 'darryl', 'danilo', 'rondo', 'alexis',  'marcas', 'dolores', 'sabes',  'anibal', 'ley',  'nancy', 'jaime', 'yolima', 'lula',  'encendida', 'recsa', 'lucena', 'navidad', 'sonny',  'alcor',  'soles', 'maya', 'lily', 'jonathan', 'ruth', 'hermes', 'fani',   'roy',  'anabel',  'creide', 'felipe', 'yela',  'omar', 'joel',  'lara',  'areli',  'amanda', 'coney',  'bella', 'rodolfo', 'mary', 'navaran', 'ocho', 'pilar',  'pili', 'mirella', 'lejia', 'margarita',   'marlene', 'kenny', 'francisco',  'salazar', 'crisia', 'erica',  'liliana',   'andy','tamara', 'daniela', 'sura',  'angela', 'becerra', 'vicky', 'john', 'freire', 'medina',  'belina',  'viviana', 'penzoi', 'esteban', 'german', 'orlando',  'brea',  'pony', 'fade', 'santiago', 'alfonso', 'nit', 'alexander', 'natalia',  'ernesto', 'imar', 'lina', 'llanes', 'cap',  'vilma', 'tina', 'sae',  'hans', 'nataly', 'lance', 'disque', 'ingrid', 'fornel', 'habria', 'aixa', 'rodriguez', 'dieci', 'celine', 'primeo',  'miriam', 'francisca', 'jordania',  'mareli','anyi',   'debora',  'yurany', 'linda', 'face', 'mariza', 'paula',  'valle', 'anel',   'noves',  'magual', 'wilmer',  'nayra', 'macha', 'nayibe', 'melissa', 'frank',  'lucas',  'zoila',  'leni', 'nestor', 'sona', 'cancer', 'aurora', 'anida',  'sanz',  'gel', 'torres', 'reste', 'rafe', 'ibarre', 'lilia', 'elba', 'barda', 'junior', 'nayebi', 'hector', 'papi', 'smith', 'rama',  'uriel', 'tania',  'mejia', 'live',  'haydee', 'solano', 'alberto',  'terres', 'abril', 'yule', 'dary',  'lizbeth',  'solari',  'blas', 'cipare', 'pudian', 'rua',  'almeda', 'calda', 'dadas', 'perez', 'arancha', 'hugo',  'ramino',  'camel', 'oris', 'judith', 'cyme', 'ania', 'daimio', 'videla', 'mailen', 'diani', 'trebol',   'garza', 'vernes', 'many', 'milena',  'paco',  'cis', 'the',  'maical', 'layme', 'austri',  'joanna',  'harris',  'nicole', 'covadonga', 'forne', 'rocio', 'nardia', 'manera', 'raul', 'deal', 'franco', 'mario', 'leiste', 'juarez',  'pedro', 'camilo', 'peras', 'monica', 'magali', 'denis', 'piedad', 'gine', 'lopera', 'lile', 'cindy', 'nedia', 'concel', 'banks', 'elida', 'caceres',  'arelis',  'darsy', 'nicolas', 'juana', 'lauri', 'selan', 'turi',  'sana', 'caldo', 'sol', 'rector', 'axa',  'begona', 'catalina', 'emilio', 'maira', 'luciana', 'ihc', 'millan', 'nino', 'neas', 'madrid',  'sun',  'berny',  'vega',  'adriana', 'liena',   'laca', 'barbara',  'manuela', 'claris', 'dayana',  'libares',  'rondon', 'oscar', 'arroz', 'marra', 'garcia', 'roger', 'run', 'narez', 'razon', 'zapata', 'max', 'leslie', 'senas', 'silvia', 'dalia', 'six', 'bike',  'ambar', 'tona', 'amelia',  'incen', 'chus', 'one', 'mauricio', 'neri',  'auria', 'nelly', 'jesus', 'lidia', 'gilbert',  'itziar',   'sico',  'concha', 'judy', 'liz', 'byron', 'cristina', 'por', 'pino', 'tesido', 'life', 'roxana',  'irma', 'noris', 'llegas',  'zaira',  'harry',  'clay', 'salvia', 'mercedes',    'gray', 'sonia',   'dora', 'solan', 'lora', 'mamen', 'valdez',  'grand', 'leis',  'liseth', 'nica', 'castro',  'vanesa', 'ivone', 'rono', 'doce', 'emanuel', 'garate',  'lourdes',  'javier', 'cecilia', 'leca', 'leidy',  'abel', 'vino', 'catherine', 'melisa', 'freno', 'gomez', 'letras', 'diana', 'saga', 'yuda', 'andrade', 'carla', 'durante', 'panera', 'andri', 'net', 'lucy', 'garre', 'megan', 'tilio', 'green', 'gerson', 'felix', 'stefani',  'yalana',  'alvan', 'lida',  'julio',  'vencia', 'fanny', 'belen',   'lazaro', 'ronal', 'gema', 'sano', 'delson', 'palito', 'karina',  'parana',  'ursula',  'nora',  'termo', 'smile', 'mateo', 'ramina', 'armando', 'mendez', 'lunas',  'lety', 'america', 'denise', 'jan',  'giovanni', 'ibera', 'bano', 'magdalena', 'kaline', 'jaen', 'oliva', 'caldes', 'anne',  'roman', 'irene', 'hiram',  'david', 'yolanda',   'kelly', 'yana', 'ricardo', 'diles', 'rodrigo', 'alzate', 'ximena',  'fernanda',  'onza',   'arturo', 'alvarez', 'send', 'iban', 'felina', 'jim', 'hilda',  'beatriz',  'leticia', 'calve', 'karim',  'jasmin', 'vidal', 'aro','antonio', 'caldeo',  'sauce', 'gracias', 'kennedy', 'matilde', 'marcelo',   'arley', 'diner', 'jorge',  'ores', 'velita',  'lissette', 'cano', 'charo', 'inmaculada',  'aida', 'granda',  'page',  'vana', 'patricia', 'amada',  'roque', 'torras', 'cristo',  'israel', 'laura', 'romina',   'virginia',  'leidata', 'rosy', 'lola',  'motin', 'edgar',   'sabina', 'nari',  'janet', 'hiper', 'yasmin', 'molina', 'bony', 'george', 'karen', 'fernando', 'sergio', 'enrique', 'naia', 'sebastian', 'erre', 'ton', 'zapia', 'gina', 'nelda', 'willy',  'amparo', 'sando', 'facial', 'fido', 'alga', 'shuster', 'rata', 'samuel', 'hare', 'karla', 'lunar', 'amor',  'axel', 'habia', 'nati', 'nelson', 'johana', 'salas', 'lancaya', 'parta', 'teresa','taire', 'senora', 'wilson', 'ronna', 'only',  'tac',  'humero', 'paty', 'seneda', 'flan',  'kimber', 'merida', 'liceo', 'retroce', 'rite', 'estefania', 'haces', 'renglon', 'wendy', 'ovalle', 'sanchez', 'ellen', 'jessica',  'jesica', 'beto',  'key',  'kenia',  'elena', 'rita', 'monza', 'marita', 'jale',  'reno', 'topa', 'sheila', 'mero', 'marlon', 'sofia', 'lelloa', 'leonardo', 'lopez', 'valeria', 'tul', 'macarena', 'noelia', 'brian', 'damian', 'moises', 'yerno', 'melchor', 'sim', 'dianis', 'nadia', 'daisy', 'nidia','jara', 'yeferson', 'igt', 'mariana', 'irla',   'lena', 'lanas', 'rachel', 'empro', 'jimena', 'roberto', 'lumia', 'cande', 'amilcar', 'cetes',  'juliana', 'gabriel', 'olier', 'sinia',  'dinar',  'villa',  'ramiro',   'rayan', 'sarah', 'cesar', 'elvira', 'rosario', 'alicia',  'yamile', 'servin', 'hernando', 'ronan', 'chirle', 'patty', 'asor',  'amalia', 'darwin', 'genesis', 'agende', 'arleque', 'filio', 'ruiz', 'race',  'kely', 'raymi', 'edison', 'lincon', 'jairo', 'salud',  'erika','mouse',  'alvaro', 'alejandro', 'mayra', 'ferney', 'milagros', 'rosana', 'lucia',   'joana', 'gloria', 'agrario',  'satia', 'kelisa',  'martinez', 'garan',  'tatiana', 'laida',  'astrid', 'janeth', 'santo', 'descardo', 'estela',  'landon', 'blanca',  'idaida', 'guru', 'salvador', 'gerald', 'mayela', 'eva', 'sativa', 'claudia', 'enero', 'angelica', 'paky', 'jimeno', 'dicar', 'gian', 'pre', 'atenas', 'katy',  'pari', 'discar', 'rey', 'lupe', 'ranera', 'luisa', 'leire',  'varela',  'marisol', 'perno', 'rendo',   'zarate',  'iman', 'alejandra',  'valentina',  'martes', 'any', 'eliven',  'arlen'}